"""Typed data structures for the Grounded RAG Generation layer.

Role boundary (docs/rag_generation_v1_report.md §1-3): Claude is an
*explainer*, never a decision-maker. Every field that carries a decision --
which service, what score, what grade, what evidence exists, what's missing
-- is produced by Python (recommender + rag.retriever) and handed to Claude
as read-only input, or assembled by Python after Claude returns. Claude only
ever fills the free-text explanation fields on ``LLMGeneratedFields``, and
even those are sanitized afterward (see ``guardrails.py``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

from pydantic import BaseModel, Field

from .models import RetrievalResult

# Korean labels for the 4 official-source sections, reused for prompt
# construction and for the "[근거: ...]" citation tags (rag_generation_v1
# _report.md §16 / rag_retrieval_v1_report.md §4).
SECTION_LABELS_KO = {
    "target": "지원대상",
    "criteria": "선정기준",
    "support": "지원내용",
    "application": "신청방법",
}

STATUS_OK = "OK"
STATUS_INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"

# Fixed, Python-authored disclaimer -- never generated by Claude, always
# present verbatim so its wording can never drift or be dropped.
SAFETY_NOTICE = (
    "이 설명은 공식 원문을 바탕으로 한 참고 안내이며, 실제 자격 여부는 거주지 읍/면/동 "
    "주민센터 또는 서비스 문의처를 통해 반드시 확인해야 해요."
)

# Deterministic fallback used whenever no application_original evidence
# exists for a service (docs/rag_retrieval_v1_report.md §3: 25/85 services
# have application_original == "[]"). Set in Python, never left to Claude to
# decide or guess (rag_generation_v1_report.md §8).
NO_APPLICATION_EVIDENCE_MESSAGE = (
    "현재 보유한 공식 정보에서는 이 서비스의 구체적인 신청방법을 확인할 수 없습니다."
)

INSUFFICIENT_EVIDENCE_MESSAGE = "현재 보유한 공식 정보에서는 확인할 수 없습니다."


@dataclass(frozen=True)
class GroundedGenerationRequest:
    """Everything Generation needs, and nothing it can invent on its own.

    ``retrieved_documents`` must already be scoped to this ``service_id`` by
    the caller (via ``rag.retriever.retrieve_for_service`` /
    ``retrieve(service_ids=[service_id])``) -- Generation does not call the
    retriever itself and never widens the evidence set.
    """

    service_id: str
    service_name: str
    user_profile_summary: str
    recommendation_level: str  # RecommendationResult.match_level.value, verbatim
    recommendation_reasons: List[str]
    confirmation_needed: List[str]
    user_question: str
    retrieved_documents: List[RetrievalResult] = field(default_factory=list)


class LLMGeneratedFields(BaseModel):
    """The ONLY thing Claude is allowed to produce -- structured-output
    schema passed to ``client.messages.parse(output_format=...)``. Every
    other field on ``GroundedAnswer`` is Python-authored."""

    summary: str = Field(description="이 서비스가 어떤 서비스인지 1-2문장 요약")
    why_recommended: str = Field(
        description="recommendation_reasons를 사용자가 이해하기 쉬운 문장으로 재서술 (새 이유를 만들지 않음)"
    )
    eligibility_explanation: str = Field(
        description="CONTEXT의 지원대상/선정기준 근거만 사용한 자격 관련 설명. 확정 표현 금지"
    )
    support_explanation: str = Field(description="CONTEXT의 지원내용 근거만 사용한 설명")
    application_explanation: str = Field(
        description="CONTEXT의 신청방법 근거만 사용한 설명. 근거가 없으면 빈 문자열"
    )
    confirmation_items: List[str] = Field(
        default_factory=list, description="사용자가 추가로 확인해야 할 항목 목록"
    )


@dataclass(frozen=True)
class EvidenceItem:
    """Python-authored evidence trace -- built directly from
    ``RetrievalResult``, never from anything Claude writes."""

    section: str
    section_label: str
    content: str
    service_id: str
    score: float

    def as_dict(self) -> dict:
        return {
            "section": self.section,
            "section_label": self.section_label,
            "content": self.content,
            "service_id": self.service_id,
            "score": self.score,
        }


@dataclass
class GroundedAnswer:
    service_id: str
    service_name: str

    summary: str
    why_recommended: str
    eligibility_explanation: str
    support_explanation: str
    application_explanation: str
    confirmation_items: List[str]

    evidence: List[EvidenceItem]
    insufficient_information: List[str]
    safety_notice: str
    status: str  # STATUS_OK | STATUS_INSUFFICIENT_EVIDENCE

    def as_dict(self) -> dict:
        return {
            "service_id": self.service_id,
            "service_name": self.service_name,
            "summary": self.summary,
            "why_recommended": self.why_recommended,
            "eligibility_explanation": self.eligibility_explanation,
            "support_explanation": self.support_explanation,
            "application_explanation": self.application_explanation,
            "confirmation_items": self.confirmation_items,
            "evidence": [e.as_dict() for e in self.evidence],
            "insufficient_information": self.insufficient_information,
            "safety_notice": self.safety_notice,
            "status": self.status,
        }
